FROM ubuntu:jammy
RUN apt-get update
RUN apt-get install -y clang llvm libelf-dev libpcap-dev build-essential make 
RUN apt-get install -y linux-tools-common linux-tools-generic
RUN apt-get install -y linux-cloud-tools-generic linux-tools-5.15.0-72-generic linux-cloud-tools-5.15.0-72-generic
RUN apt-get install -y gcc-multilib